# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
   disable_csrf_role: ROLE_API
   param_fetcher_listener:  true
   allowed_methods_listener:  true
   routing_loader:
        enabled: false               
        default_format: json
   view:
       mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/json;version=1.2']
       view_response_listener:  'force'
       formats:
           xml:  true
           json: true
       templating_formats:
           html: true
   exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
   format_listener:
       rules:
           - { path: '^/api', prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
           - { path: '^/', prefer_extension: true, fallback_format: html, priorities: [ json, html ] }
   access_denied_listener:
       json: true
   body_listener:
       default_format: json
