# fos_js_routing:
#   routes_to_expose:
#     [
#       get_familiak,
#       get_azpifamiliak,
#       get_fitxa,
#       fitxafamilia_edit,
#       api_fitxafamiliahasorden,
#       api_fitxafamilianextorden,
#       fitxafamilia_delete,
#       familia_delete,
#     ]
