twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        zzoo_aplikazioaren_API_url: "%zzoo_aplikazioaren_API_url%"
    form_themes:
        - bootstrap_3_layout.html.twig
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    paths:
        "%kernel.project_dir%/templates": FOSRest