services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    UserBundle\Controller\SecurityController:
        arguments:
            - '@Symfony\Component\Security\Csrf\CsrfTokenManagerInterface'
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
            - '@FOS\UserBundle\Model\UserManagerInterface'
        tags: ['controller.service_arguments']